### ISSUE TITLE
感谢大大，项目起来了，但是没有build吗？😂build报错

### ISSUE THREAD

**Issue by moker-monkey** [myliang/fish-admin#1]
ERROR in static/js/vendor.f0ab96bf65deabaaff92.js from UglifyJs
Unexpected token: name (createElement) [./node_modules/fish-ui/src/components/message.js:4,0][static/js/vendor.f0ab96bf65deabaaff92.js:19633,4]

**Comment by myliang** [comment]
uglifyJS 编译不支持es6语法
也可以参考一下这个： http://blog.csdn.net/hayre/article/details/77231568

**Comment by moker-monkey** [comment]
好的谢谢，我是这样解决的，就build完成了
`{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'),resolve('/node_modules/fish-ui/')]
      }`
